{"CONSUMER_KEY":"AqjeX5B0nWxL5vsogP3qfeWIb",
"CONSUMER_SECRET":"qYT7jMOdRS6GFIJkBUW1YRDHA1Wdsn3CKQiRbVt7IulbXaZ7fo",
"ACCESS_TOKEN":"834101552994406400-ctAxrncLcKFoJdBmEldCABly9p54edR",
"ACCESS_TOKEN_SECRET":"99ktRlsijP4O769q7CipRIWjzi4pfVfyPYsSy5Eul9IVj"}